### ISSUE TITLE
Custom Fields only Using First Value Char

### ISSUE THREAD

**Issue by BenChirlin** [scottgonzalez/node-wordpress#12]
Hello. Thank you so much for the library! It's working fantastically however I'm having issues creating a new post with a custom fields. They seem to only set the first character of my value field to both the key and value...see below.

```
client.newPost( {
			author: "string",
			name: "string",
			content: "string",
			title: "string",
			excerpt: "string",
			date: new Date(),
			customFields: { 'key': 'value' }
		}, function( err, id ) {}
);
```

So for example the new post is created but the key is just 'v' and the value is also 'v'.

Any help or examples you could provide would be much appreciated. Thank you!

**Comment by BenChirlin** [comment]
Never mind. Found the proper structure. For those curious, the `customFields` value needs to appear as follows:

```
customFields: [
	{ key: 'cyphon', value: 'cyphon' },
	{ key: 'byline', value: noms[ index ].author }
]
```

On a related note it took me some finagling to figure out the term structure which goes like this for reference:

```
termNames: {
	'category': [ 'magazine' ],
	'post_tag': [ 'issue ]
},
```

Didn't have luck with the `terms` argument though I tried it. Probably just needed to tweak it a bit.

**Comment by scottgonzalez** [comment]
Correct. These behave as exactly as documented on https://codex.wordpress.org/XML-RPC_WordPress_API/Posts#wp.newPost.
