### ISSUE TITLE
Support for wp.uploadFile?

### ISSUE THREAD

**Issue by f1nnix** [scottgonzalez/node-wordpress#13]
Hi, Scott, thank you for awesome lib,

do you have plans to support wp.uploadFile method to upload images to WP?

**Comment by f1nnix** [comment]
#14 added quick pull request

**Comment by MichielDeMey** [comment]
I guess we can close this issue then? :)

**Comment by scottgonzalez** [comment]
Yup :-) I must've missed this when landing the PR.
