### ISSUE TITLE
Support for unauthenticated calls?

### ISSUE THREAD

**Issue by lingz** [scottgonzalez/node-wordpress#15]
Is there a way to instantiate a client in the case where the API user is public, and just wants to operate in read-only mode for example?

**Comment by scottgonzalez** [comment]
I believe you'd have to write your own custom XML-RPC methods as a WordPress plugin in order to do that. If you look at `wp.getPost` for example, `username` and `password` are required fields: https://codex.wordpress.org/XML-RPC_WordPress_API/Posts#wp.getPost
