### ISSUE TITLE
Retrieving Authors Name

### ISSUE THREAD

**Issue by jaylaw81** [scottgonzalez/node-wordpress#22]
The getPosts / getPost calls, only return the author ID. Is it possible to have those mapped to return the actual author display name

**Comment by scottgonzalez** [comment]
You'll need to go through the `wp.getUser` API to get the display name. That functionality hasn't been implemented yet, but you can go through the generic `client.authenticatedCall()` for now. There's a PR that adds the user methods (#11), but it was waiting for an update. I'll work on getting that reviewed and merged.

**Comment by scottgonzalez** [comment]
If you need help getting the `wp.getUser` call to work before #11 is merged, just let me know and I'll put together some sample code.
