### ISSUE TITLE
Dependencies module update

### ISSUE THREAD

**Issue by nczz** [scottgonzalez/node-wordpress#23]
Hi

[node-xmlrpc](https://github.com/baalexander/node-xmlrpc/releases) has been released v1.3.1 in `2015-05-23` and update this module can fix the WordPress 4.3.1 xmlrpc TITLE error.

**Comment by scottgonzalez** [comment]
Can you please elaborate on what error you're referring to? Steps to reproduce would be ideal.

**Comment by nczz** [comment]
@scottgonzalez Sorry, I can't. I am trying to redo this issue again, but nothing happened.. It works fine!
So...please forgot the error.
