### ISSUE TITLE
newPost doesnt insert post and gives no output

### ISSUE THREAD

**Issue by tomtom87** [scottgonzalez/node-wordpress#24]
Trying to connect to my WP and set a post. I tried

```js
wpClient.newPost({
						title: details["title"],
						content: details["content"]}, function( error, data ){
							console.log(arguments);
					});
```

With all valid data, verified in the repl debugger.

```js
> wpClient
{ rpc: 
   { options: 
      { host: 'xxx.xxx',
        port: 80,
        path: '/xmlrpc.php',
        headers: [Object],
        method: 'POST' },
     isSecure: false },
  blogId: 0,
  username: 'xxxx',
  password: 'xxxx' }
```

**Comment by scottgonzalez** [comment]
Sorry, but there's nothing I can do to debug this without actually connecting to your server. Nobody else has been having a problem like this.

**Comment by tomtom87** [comment]
@scottgonzalez  that's really convenient for them and strange for me I guess. This is a real problem for me, your class is unusable with WP 4.5.1 - no output at all from the functions. What access do you need to my server?

**Comment by scottgonzalez** [comment]
Do you mean 4.3.1?
