### ISSUE TITLE
Create example that uses taxonomies

### ISSUE THREAD

**Issue by scottgonzalez** [scottgonzalez/node-wordpress#29]
Adding taxonomies to a post isn't super obvious. There should be an example of how to do this.

**Comment by raurir** [comment]
I have created an example, made a branch etc, but could not push my branch (remote permission denied). Anyway here is working example, that also auto publishes the post too:

```javascript
var wordpress = require( "../" );

var client = wordpress.createClient({
	url: "my-site.com",
	username: "admin",
	password: "secret"
});

client.newPost({
	title: "My Second Post",
	content: "Publishing to WordPress from node.js sure is fun!",
	status: "publish",
	termNames: {
		"category": ["Javascript", "Node"],
		"post_tag": ["api", "fun", "js"]
	}
}, function( error, data ) {
	console.log( arguments );
});
```

**Comment by scottgonzalez** [comment]
Thanks! That example looks good.

> I have created an example, made a branch etc, but could not push my branch (remote permission denied).

Correct, you don't have permission to push to my repo. You can follow the steps in GitHub's [Using pull requests](https://help.github.com/articles/using-pull-requests/) article to see the process for submitting the new example.

**Comment by scottgonzalez** [comment]
Thanks!
