### ISSUE TITLE
Can I know how to use getPosts function?

### ISSUE THREAD

**Issue by aisinvon** [scottgonzalez/node-wordpress#33]
```javascript
var data = {title: 'xxx'};
client.getPosts({ "title": data.title }, ["id"], function(gErr, gPosts) {
    console.log(data.title, 'post length: ', gPosts, '.=== gErr ', gErr);
});

```
I learned your demo code, however I still can't get how to use getPosts function working properly. Could you please tell me my code above is right or not? Thanks.

**Comment by scottgonzalez** [comment]
Can you please explain what's not working? Are you getting errors? Are you getting posts but not the posts you expect?

The syntax is correct, but the code is not. You cannot filter on title. See https://codex.wordpress.org/XML-RPC_WordPress_API/Posts#wp.getPosts

**Comment by aisinvon** [comment]
Thanks response so quickly. The issue is not getting the posts I expect. 

```javascript
var data = {title: 'xxx'};
client.getPosts({ "title": data.title }, ["id"], function(gErr, gPosts) {
    console.log(data.title, 'post length: ', gPosts, '.=== gErr ', gErr);
});
```
The console log is:

![160522-0003](https://cloud.githubusercontent.com/assets/1295007/15454197/f331e1c4-2063-11e6-9113-665ae275ae08.png)

I didn't understand what's the reason. :) Thanks.

**Comment by aisinvon** [comment]
Ok, thanks. Then is there any function to detect which post I want to insert to DB is already in DB or not?

**Comment by scottgonzalez** [comment]
No, but you can check on your own by looking at the posts that come back and checking if the title matches.

If you're managing your entire site through node, you might want to look at [Gilded WordPress](https://github.com/scottgonzalez/gilded-wordpress) which will track updates for you.
