### ISSUE TITLE
client.getPosts filter is optional, but if you don't pass it, the call returns []

### ISSUE THREAD

**Issue by satyavh** [scottgonzalez/node-wordpress#34]
reproduce:

1. call client.getPosts without any filter, it returns []
2. call client.getPosts with a filter, it returns the posts

**Comment by scottgonzalez** [comment]
The [example](https://github.com/scottgonzalez/node-wordpress/blob/master/examples/get-posts.js) works just fine for me.

**Comment by satyavh** [comment]
Sorry, you're right. I must have made a type or something
