### ISSUE TITLE
Is it possible to pipe an img to fileUpload?

### ISSUE THREAD

**Issue by satyavh** [scottgonzalez/node-wordpress#35]
I'm trying to figure out if I can download an external image from a url, and pipe the result directly to the client.uploadFile function. Is that possible?

**Comment by scottgonzalez** [comment]
That's not currently possible. I believe that adding support for this would require fully buffering the file anyway. I don't think this is too common (I haven't heard of anyone else wanting this behavior) so I'm not inclined to implement it right now.

**Comment by satyavh** [comment]
Ok clear, thanks for your quick response. Btw, awesome package!
