### ISSUE TITLE
How to use node to get form entries from wordpress

### ISSUE THREAD

**Issue by hadiab** [scottgonzalez/node-wordpress#38]
##How to use node to get form entries from wordpress
my client had a wordpress site and i need to get the form entries from the word press
i work with node and i use a wordpress package for node
[node-wordpress]( https://github.com/scottgonzalez/node-wordpress)
but i can just take the posts, can any one help me.. thanks..

**Comment by scottgonzalez** [comment]
I'm not sure what you mean by form entries. Please provide more details.

**Comment by hadiab** [comment]
Like contact form .. Can i get the entires for that form

**Comment by scottgonzalez** [comment]
Without knowing how those are stored, I can't answer that question. There's certainly nothing about contact forms in https://codex.wordpress.org/XML-RPC_WordPress_API. You'll probably need to write a custom XML-RPC method as a WordPress extension to expose that data. You'll then be able to use node-wordpress to call the custom method using [`client.call()`](https://github.com/scottgonzalez/node-wordpress#clientcall-method--args--callback-) or [`client.authenticatedCall()`](https://github.com/scottgonzalez/node-wordpress#clientauthenticatedcall-method--args--callback-).
