### ISSUE TITLE
uploadFile callback 

### ISSUE THREAD

**Issue by onlytalk** [scottgonzalez/node-wordpress#39]
I try to use this one:

> var fs = require( "fs" );
> var wordpress = require( "../" );
> 
> var client = wordpress.createClient({
> 	url: "my-site.com",
> 	username: "admin",
> 	password: "secret"
> });
> 
> // "Aurora Borealis" by Frederic Edwin Church
> // Licensed under Public Domain via Wikimedia Commons
> var filename = "aurora-borealis.jpg";
> var file = fs.readFileSync( filename );
> client.uploadFile({
> 	name: filename,
> 	type: "image/jpg",
> 	bits: file
> }, function( error, data ) {
> 	console.log( arguments );
> });

but as callback i take only

> [object Arguments]

How to take link to this new-uploaded image?

**Comment by scottgonzalez** [comment]
I have no idea what you're using that you'd get `[object Arguments]` as output, but if you look at the actual data, you'll see that `data.url` is what you're looking for.
