### ISSUE TITLE
Emoji support

### ISSUE THREAD

**Issue by g-gabber** [scottgonzalez/node-wordpress#40]
Recently I faced the problem, when a post content contains emoji unicode character it fail with 
```
Error: Invalid character (�) in string:
```
The exception is thrown in node-xmlrpc. There is already an opened [issue](https://github.com/baalexander/node-xmlrpc/issues/122) which refers an issue in [xmlbuilder-js](https://github.com/oozcitak/xmlbuilder-js/issues/98).

Is there any possibility to push them to fix it?
Or is there a way some how to apply a path in sub dependency? 

Best Regards

**Comment by scottgonzalez** [comment]
> Is there any possibility to push them to fix it?

The way to push them to fix it would be to send a PR that makes it work. Is this something you're interested in doing? If not, I can dig in and try to get it fixed.

**Comment by g-gabber** [comment]
I have already a fix, I need to write some tests. I will try to finish it tomorrow.

**Comment by scottgonzalez** [comment]
That's great to hear. If you run into any problems, I'm happy to help.

**Comment by g-gabber** [comment]
I pushed a [pull request ](https://github.com/baalexander/node-xmlrpc/pull/127)

**Comment by g-gabber** [comment]
Good news, they accepted my [fix](https://github.com/baalexander/node-xmlrpc/pull/127) and promises to release it under  version 1.3.2 this week.

**Comment by scottgonzalez** [comment]
That's great. I can do a release as soon as 1.3.2 is out.

**Comment by patricklodder** [comment]
I just pushed 1.3.2 to npm.

**Comment by scottgonzalez** [comment]
Thanks. I just published v1.2.2 to npm :-)
