### ISSUE TITLE
You are my Hero!

### ISSUE THREAD

**Issue by helloncanella** [scottgonzalez/node-wordpress#42]
Hey Man, thanks for this package. You really saved my relation with wordpress!

I hate PHP, and I have ton of requests to develop wordpress websites and blogs. To discover I'm, now, able to write my projects in peace using without to deal one unique line of PHP is extremely pleasant.

I really thank you.

**Comment by scottgonzalez** [comment]
Thanks :-)

If you're managing a bunch of sites, you might want to also check out [Gilded WordPress](https://github.com/scottgonzalez/gilded-wordpress/) which builds on top of this to make managing an entire site super simple.
