### ISSUE TITLE
Using uploadFile with Blob

### ISSUE THREAD

**Issue by subatomicceo** [scottgonzalez/node-wordpress#44]
Ok so I'm running Meteor, with Dropzone, and uploading images to an AWS S3 bucket. After the Dropzone callback I have an image resizer which returns a Blob. I'm trying to base64 encode, and upload the Blob. Everything seems to work fine but when previewing the image it shows as a blank square? I'm assuming there is an error with my base64 encoded string? I've included some example code to help illustrate my problem. Any help would be greatly appreciated thanks!

```
const wordpress = require( "../" );

let client = wordpress.createClient({
	url: "my-site.com",
	username: "admin",
	password: "secret"
});

function blobToBits(blob, callback){
    let reader;
    reader = new FileReader();
    reader.onload = callback;
    reader.readAsDataURL(blob);
}

IMAGERESIZER({
    callback: function(blob){
        blobToBits(blob, function(e){
            let bits = btoa(e.target.result),
            params = { name: blob.name, type: blob.type, bits: bits}; 
            client.uploadFile(params, function( error, data ) {
	            console.log( error, data );
            });
        });
    }
});
```

**Comment by g-gabber** [comment]
bits should be a Uint8Array, try this 
```js
params = { name: blob.name, type: blob.type, bits: new Buffer(e.target.result)}; 
```

**Comment by subatomicceo** [comment]
@g-gabber thanks so much! Just a note to anyone else attempting the same thing you have to encode the blob to base64, and then to a Unit8array.

`
const wordpress = require( "../" );

let client = wordpress.createClient({
    url: "my-site.com",
    username: "admin",
    password: "secret"
});

function blobToBits(blob, callback){
    let reader;
    reader = new FileReader();
    reader.onload = callback;
    reader.readAsDataURL(blob);
}

IMAGERESIZER({
    callback: function(blob){
        blobToBits(blob, function(e){
            let bits = e.target.result.replace(/^data:image\/\w+;base64,/, ''),
            params = { name: blob.name, type: blob.type, bits: ''};
           params.bits =  new Buffer(bits, 'base64');
            client.uploadFile(params, function( error, data ) {
                console.log( error, data );
            });
        });
    }
});
`
