### ISSUE TITLE
How to get posts with type=page?

### ISSUE THREAD

**Issue by yasaman93** [scottgonzalez/node-wordpress#48]
I have a wordpress site that all of its posts have post_type=page, how can I get these posts?

**Comment by scottgonzalez** [comment]
Use [`getPosts()`](https://github.com/scottgonzalez/node-wordpress#clientgetposts-filter--fields-callback-) with a `filter` on `type` (see the list of [fields](https://github.com/scottgonzalez/node-wordpress#posts-1)).

```js
client.getPost({ type: 'page' }, function (error, posts) { .. })
```
