### ISSUE TITLE
post return limit?

### ISSUE THREAD

**Issue by AbdelhamidAhmed** [scottgonzalez/node-wordpress#53]
I'm trying to get all the posts of type product in my wordpress using this code

```
client.getPosts({
    type: 'product'
}, function(error, products) {
  products.forEach(function(product) {
    console.log(product.name);
  })
});

```
but it just gets 10 posts instead of all the items I have, how can I get all? Is there a pre determined limit?

**Comment by scottgonzalez** [comment]
See the [WordPress docs](https://codex.wordpress.org/XML-RPC_WordPress_API/Posts#wp.getPosts), specifically the `number` and `offset` filters.
