### ISSUE TITLE
Featured Image issue

### ISSUE THREAD

**Issue by kartboy16** [scottgonzalez/node-wordpress#55]
Awesome package!!

I have an issue where I am sending the same post with featured image to multiple wordpress sites.  I ran into an issue where, on some sites, the feature image is fine whereas others the featured image is not set.  When I check the wp site for the featured image, it's actually in the media, just not linked to the post.  

`client.newPost(postVals, function(err, id) {`
    `client.uploadFile({`
             `name: name,`
             `type: type,`
             `bits: buffer,`
             `postId: id,`
             `overwrite: true,`
         `}, function (err, file) {`
             `console.log("File successfully uploaded", file);`
         `});`    
`});`

When I look at the file in the callback function, the file.parent shows the correct postId.  

Not sure why it sets on some WP sites and not others...

**Comment by scottgonzalez** [comment]
Based on the description, this sounds like node-wordpress is working properly and there's an issue with some of the WordPress installs. That's not something I can debug.

**Comment by kartboy16** [comment]
Finally figured out the issue.  

I had to editPost after the image finished uploading and update the thumbnail field with the image id.

**Comment by jremi** [comment]
How did you fix this?

I am not getting an error and it appears to be picking up the correct post. I have confirmed that I have entered the correct post parent id and correct media image id... Nothing happens.

```
    var wpPostId = "996";
    var wpMediaFileId = "1041";
    wpclient.editPost(wpPostId,{
        "featured_media" : wpMediaFileId
    },function(error){
        if(error){
            console.log('Error updating featured image of post - ' + error);
        }
    });
```

**Comment by jremi** [comment]
Resolved...
```

wpclient.editPost(id, {
   thumbnail : fileData.attachment_id
}, function(error){});
```
