### ISSUE TITLE
Give me an example of how to use this method

### ISSUE THREAD

**Issue by DeeSouza** [scottgonzalez/node-wordpress#56]
I didn't understand what I have to pass to the `filter` argument to the following method:

`client.getPosts( [filter] [, fields], callback )`

I did:

```
var postsChatbot = {
   'numberposts'   : 3,
   'category_name' : 'entrevistas',
   'post_type'     : 'post',
   'include'   : [1,2,3]
};
```

Doesn't work!

Thanks!

**Comment by scottgonzalez** [comment]
`numberposts` should be `number, `category_name` and `include` are not a valid filters. See [the WordPress docs](https://codex.wordpress.org/XML-RPC_WordPress_API/Posts#Parameters_2) for details.

**Comment by DeeSouza** [comment]
How can I use your library to retrieve a list of specific posts? Is that possible using getPosts or must I have to getPost one by one?

I was using this docs:
https://developer.wordpress.org/reference/functions/get_posts/

**Comment by scottgonzalez** [comment]
You have to use `getPost` or write your own custom XML-RPC method in WordPress. The docs you linked to are for a PHP method within WordPress itself.
