### ISSUE TITLE
Is this possible to load whole wordpress website inside nodejs using this module ?

### ISSUE THREAD

**Issue by rushabhmadhu2016** [scottgonzalez/node-wordpress#59]
Hello

I appreciate your work. I have one issue regarding this, I am not sure it is any issue in your development or not but i thought i must have to ask your before comming to any conclussion.

consider that my node js app is working at http://127.0.0.1:8080
Now at http://127.0.0.1:8080/blogs i want to open my blogs website of Apace/PHP/Wordpress website.

It is possible using this way ?

**Comment by scottgonzalez** [comment]
This is a client for interacting with a WordPress site. It is *not* a node module for running a WordPress site.
