### ISSUE TITLE
how to filter post on the basis of custom fields? 

### ISSUE THREAD

**Issue by KhizerRehan** [scottgonzalez/node-wordpress#62]

**Comment by KhizerRehan** [comment]
```
  client.getPosts({
    status: 'publish',
  },[{
     "key": "professor_name",
     "value": "Bilal"
    }],
  function( err, data ) {
    console.log( data );
    res.send(data);
  });
```

**Comment by scottgonzalez** [comment]
That is not supported by [the WordPress API](https://codex.wordpress.org/XML-RPC_WordPress_API/Posts#Parameters_2). You'd need to build a custom XML-RPC method within WordPress to support that. You can see how to do this in [gilded-wordpress](https://github.com/scottgonzalez/gilded-wordpress/blob/master/gilded-wordpress.php).
