### ISSUE TITLE
Found 0 posts! []

### ISSUE THREAD

**Issue by theranajayant** [scottgonzalez/node-wordpress#67]
The website does have 4 blog posts and 3 pages but executing this code returns np blog post. Here is the exact code. (credentials removed)

```
var express=require("express")
wordpress = require( "wordpress" );
var app=express()

var client = wordpress.createClient({
    url: "https://abc.com",
    username: "nodebot",
    password: "*****"
});


client.getPosts(function( error, posts ) {
    console.log( "Found " + posts.length + " posts!" );
    console.log(posts);
});
```

**Returns:**
Found 0 posts!
[]

**Comment by scottgonzalez** [comment]
I can't really do anything to help based on this. The module is working for many people.

**Comment by theranajayant** [comment]
For some reason, It started working after a few attempts. Thanks for your support and here is the weird part. I got a new issue while trying to upload an image. It will be helpful if you can suggest any solution. 

Note: I tried googling but they explained on plugin level, not on API.


`
//function uploadFile(){}
fs.readFile("abc.png",(error, data)=>{
    
    if(!error){ 
        console.log(data)
    }

    else{
        console.log(error)
    }

var dataPacket={
        name:"botimage1",
        type:"png",
        bits:data, //the bots data
        postId:"" //attach image to specific post id//used in wp to delete unused image later
        }
client.uploadFile( dataPacket, (error,file)=>{

    if(!error){ 
            console.log(file)
        }
    else console.log(error)
})
})`

**Output on Console:** (Also, Screenshot attached)
{
  code: 500,
  faultCode: 500,
  faultString: 'Could not write file botimage1 (Sorry, this file type is not permitted for security reasons.).'
}

Note: I tried giving ".png" in type as well but it didn't work.
![Screenshot 2020-01-20 at 10 41 30 AM](https://user-images.githubusercontent.com/12654266/72700300-8c55d500-3b71-11ea-9ca3-6af2a1935604.png)
