### ISSUE TITLE
client.newPost issue - Error: Invalid XML-RPC message

### ISSUE THREAD

**Issue by Bek81** [scottgonzalez/node-wordpress#7]
Hi,
this is my configuration to test (in nodeJS server) the method client.newPost
...
var np = {
	type: 'my_type',
	title: 'My title',
	status: 'publish',
	customFields: [
		{'custom-post-1': 'false'}, // tried also with {key: 'custom-post-1'', value: 'false'},
		{'custom-post-2': 'test'}, //...
	]
}
...
client.newPost(np,function(error,id) {
	if (error) console.log('>>> ' + error);
	else console.log(id);
});

(I set every mandatory custom field)

The exit was:
>>> Error: Invalid XML-RPC message

Can you help me to know the right config pls?

tnx a lot!!!

p.s.:
client.getPost works!

**Comment by harlantwood** [comment]
We had the same issue, and changing from http to https solved it!  That is the WP URL had to start with `https://`.

**Comment by Sharp6** [comment]
Thanks harlantwood, I had this issue as well and solved it by adding https.
