### ISSUE TITLE
Sorry, this file type is not permitted for security reasons.

### ISSUE THREAD

**Issue by sucheep-s** [scottgonzalez/node-wordpress#70]
Hi guys, I do an upload job but it returns me error,

> Error: XML-RPC fault: Could not write file my_file (Sorry, this file type is not permitted for security reasons.).

Here is my code

![Snip25630424_5](https://user-images.githubusercontent.com/8954519/80189808-7c043900-863d-11ea-9f74-6a2d2e372ab8.png)

I've found a solution on the internet that I can put a code

> define(‘ALLOW_UNFILTERED_UPLOADS’, true);

into the config.php

This solution can solve the issue but almost comments I've read don't recommend to use this solution due to the security issue.

Is there another solution to solve. Or I can go this way without any concern ?

**Comment by scottgonzalez** [comment]
That's really up to you, but I will say that I used `ALLOW_UNFILTERED_UPLOADS` for all jQuery sites.
