### ISSUE TITLE
How to make post creating synchronous?

### ISSUE THREAD

**Issue by jalamba4everkisa** [scottgonzalez/node-wordpress#71]
Have no idea how to force cycle to work in order, one by one.

`var wordpress = require( "wordpress" );

var client = wordpress.createClient({
    url: "localhost/test",
    username: "root",
    password: "12345"
});

for(let x = 0; x < 1000; x++){
    client.newPost({
        title: x,
        content: x,
        status: 'publish'
    }, function( error, file ) {
    })
}`

**Problem**

Cycle working not in order.
Not all posts have been created.

**Comment by scottgonzalez** [comment]
Please research asynchronous programming.

**Comment by jalamba4everkisa** [comment]
Found solution, could be helpful.

`var wordpress = require( "wordpress" );


var client = wordpress.createClient({
    url: "localhost/test",
    username: "root",
    password: "12345"
});

function post(x){
    return new Promise(function(resolve,reject){
        client.newPost({
            title:x,
            content:x,
            status:"publish"
        }, function(error, data){
            resolve();
        });
    });
}

async function postCycle(n) {
    for (let i = 0; i < n; i++){
        await post(i);
    }
}

postCycle(1000);`
