### ISSUE TITLE
getPosts pagination

### ISSUE THREAD

**Issue by konsumer** [scottgonzalez/node-wordpress#72]
Is there a way to get more than the first page of posts? I have a wordpress site that has 26 posts, and I only get back 10 records from `getPosts()`.

**Comment by konsumer** [comment]
It's a bit hacky, but this works:

```
getPosts({ number: 10000 })
```

**Comment by scottgonzalez** [comment]
Use `offset` for pagination: https://codex.wordpress.org/XML-RPC_WordPress_API/Posts#Parameters_2
