### ISSUE TITLE
client.uploadFile can't set all properties of the image you upload

### ISSUE THREAD

**Issue by Lady-vamp** [scottgonzalez/node-wordpress#74]
Using client.uploadFile to upload a photo, is it possible to set the photo's description and the alt of the image? Right now I can't find a proper way to do it

**Comment by scottgonzalez** [comment]
As far as I can tell, the [WordPress API](https://codex.wordpress.org/XML-RPC_WordPress_API/Media#wp.uploadFile) does not support setting description or alt.
