### ISSUE TITLE
customFields [client.editPost] update custom field BUG

### ISSUE THREAD

**Issue by go2usman** [scottgonzalez/node-wordpress#77]
- If some **customFields** is empty then edit or update is working perfectly.
- But the **issue** is when it is already filled by some value and want to update it again then it is not working in other way when some value is already there in custom filed then it is not working for update those customFields.
- 
![Screenshot from 2024-06-06 00-40-06](https://github.com/scottgonzalez/node-wordpress/assets/84284941/4833e105-c958-4af4-8552-173d6588bbb3)
- 
and when I run for 'states' code then it is working fine (because states field is empty you can check in screenshot)

` client.editPost(
        pageId,
        {
            type: "page",
            title: "update testing", 
            status: "update",
            content:"Hello ",
            customFields: [
                { key: "states", value: ["delhi"] },
            ],.....`
![Screenshot from 2024-06-06 00-46-53](https://github.com/scottgonzalez/node-wordpress/assets/84284941/b933c89d-a1bd-4545-80ad-16d6b6b10fdd)

but when I again run with diffrent value like mumbai then it is not working(because field is not empty now)

` client.editPost(
        pageId,
        {
            type: "page",
            title: "update testing", 
            status: "update",
            content:"Hello ",
            customFields: [
                { key: "states", value: ["mumbai"] },
            ],.....`

**Comment by scottgonzalez** [comment]
This is just how the WordPress API works. If you want to update an existing custom field, you must provide the ID of the custom field. If you use `client.getPost()`, you'll see the IDs in the response.
